version: '3.8'

services:
  dev-db:
    image: postgres:15
    ports:
      - 5454:5432
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: express
    networks:
      - musteat
networks:
  musteat:
